/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import it.uniroma1.lcl.babelfy.commons.BabelfyParameters;

public class ExampleTokenTest {
    @Test public void testSomeLibraryMethod() {
        // ExampleToken classUnderTest = new ExampleToken();

        BabelfyParameters bfyParams1 = ExampleToken.getParams("BN", "ALL");

        assertEquals(BabelfyParameters.SemanticAnnotationResource.BN,
                     bfyParams1.getAnnotationResource());
        assertEquals(BabelfyParameters.SemanticAnnotationType.ALL,
                     bfyParams1.getAnnotationType());

        BabelfyParameters bfyParams2 = ExampleToken.getParams("WN", "CONCEPTS");

        assertEquals(BabelfyParameters.SemanticAnnotationResource.WN,
                     bfyParams2.getAnnotationResource());
        assertEquals(BabelfyParameters.SemanticAnnotationType.CONCEPTS,
                     bfyParams2.getAnnotationType());
    }
}
